### ISSUE TITLE
required artifact missing : org.apache.maven:super-pom:jar:2.0

### ISSUE THREAD

**Issue by coldnew** [pdelong42/rrd4clj#1]
I came up with this when running `lein deps`:

$lein deps 
Downloading: org/clojars/maoe/rrd4clj/0.0.0/rrd4clj-0.0.0.pom from repository central at http://repo1.maven.org/maven2
Unable to locate resource in repository
Downloading: org/clojars/maoe/rrd4clj/0.0.0/rrd4clj-0.0.0.pom from repository clojars at http://clojars.org/repo/
Unable to locate resource in repository
Downloading: org/clojars/maoe/rrd4clj/0.0.0/rrd4clj-0.0.0.jar from repository central at http://repo1.maven.org/maven2
Unable to locate resource in repository
Downloading: org/clojars/maoe/rrd4clj/0.0.0/rrd4clj-0.0.0.jar from repository clojars at http://clojars.org/repo/
Unable to locate resource in repository
## Exception in thread "main" Unable to resolve artifact: Missing:

1) org.clojars.maoe:rrd4clj:jar:0.0.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojars.maoe -DartifactId=rrd4clj -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojars.maoe -DartifactId=rrd4clj -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:pom:2.0
    2) org.clojars.maoe:rrd4clj:jar:0.0.0

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  clojars (http://clojars.org/repo/)

 (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$script_opt.invoke(main.clj:270)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:377)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
## Caused by: Unable to resolve artifact: Missing:

1) org.clojars.maoe:rrd4clj:jar:0.0.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojars.maoe -DartifactId=rrd4clj -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojars.maoe -DartifactId=rrd4clj -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:pom:2.0
    2) org.clojars.maoe:rrd4clj:jar:0.0.0

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  clojars (http://clojars.org/repo/)

```
at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:268)
at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:168)
at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:751)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:265)
at leiningen.deps$do_deps.invoke(deps.clj:133)
at leiningen.deps$deps.doInvoke(deps.clj:198)
at clojure.lang.RestFn.invoke(RestFn.java:410)
at clojure.lang.Var.invoke(Var.java:365)
at clojure.lang.AFn.applyToHelper(AFn.java:161)
at clojure.lang.Var.applyTo(Var.java:482)
at clojure.core$apply.invoke(core.clj:542)
at leiningen.core$apply_task.invoke(core.clj:264)
at leiningen.core$_main.doInvoke(core.clj:331)
at clojure.lang.RestFn.invoke(RestFn.java:410)
at clojure.lang.AFn.applyToHelper(AFn.java:161)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at clojure.core$apply.invoke(core.clj:542)
at leiningen.core$_main.invoke(core.clj:334)
at user$eval42.invoke(NO_SOURCE_FILE:1)
at clojure.lang.Compiler.eval(Compiler.java:5424)
... 11 more
```
## Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:

1) org.clojars.maoe:rrd4clj:jar:0.0.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojars.maoe -DartifactId=rrd4clj -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojars.maoe -DartifactId=rrd4clj -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:pom:2.0
    2) org.clojars.maoe:rrd4clj:jar:0.0.0

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  clojars (http://clojars.org/repo/)

```
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:360)
at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:263)
... 35 more
```

**Comment by pdelong42** [comment]
Hi @coldnew,
Please give this another try when you get a chance.  I have the project using Leiningen now, which should implicitly handle all the Maven configuration itself (which hopefully fixes the issues you were seeing).

It's been a while, so I'd understand if you've moved on to other things.
